# Generated by Django 4.0.6 on 2022-07-07 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('port', models.IntegerField()),
                ('last_presence', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
